const MAIN_DIR = 'src/main/';
const TEST_DIR = 'src/test/';
const YB_VERSION = '2.18.2.1-b1';

const Types = {
  MONOLITH: 'monolith',
  MICROSERVICE: 'microservice',
  GATEWAY: 'gateway',
  APPLICATION_TYPE: 'applicationType',
  AUTHENTICATION_TYPE: 'authenticationType',
  SQL: 'sql',
  YSQL: 'ysql',
  YCQL: 'ycql',
  POSTGRESQL: 'postgresql',
  CASSANDRA: 'cassandra',
  H2_DISK: 'h2Disk',
  H2_MEMORY: 'h2Memory',
  JWT: 'jwt',
  OAUTH2: 'oauth2',
  SESSION: 'session',
  BASE_NAME: 'baseName',
  MAVEN: 'maven',
  GRADLE: 'gradle',
  ELASTICSEARCH: 'elasticsearch',
  PROMETHEUS: 'prometheus',
  ELK: 'elk',
  BLUEPRINT: 'blueprint',
  BLUEPRINTS: 'blueprints',
  BUILD_TOOL: 'buildTool',
  CACHE_PROVIDER: 'cacheProvider',
  NO_CACHE_PROVIDER: 'no',
  CLIENT_FRAMEWORK: 'clientFramework',
  CLIENT_PACKAGE_MANAGER: 'clientPackageManager',
  CLIENT_THEME: 'clientTheme',
  CLIENT_THEME_VARIANT: 'clientThemeVariant',
  WITH_ADMIN_UI: 'withAdminUi',
  CREATION_TIMESTAMP: 'creationTimestamp',
  DATABASE_TYPE: 'databaseType',
  DEV_DATABASE_TYPE: 'devDatabaseType',
  DTO_SUFFIX: 'dtoSuffix',
  EMBEDDABLE_LAUNCH_SCRIPT: 'embeddableLaunchScript',
  ENABLE_HIBERNATE_CACHE: 'enableHibernateCache',
  ENABLE_SWAGGER_CODEGEN: 'enableSwaggerCodegen',
  ENABLE_TRANSLATION: 'enableTranslation',
  ENTITY_SUFFIX: 'entitySuffix',
  EXPERIMENTAL: 'experimental',
  GATEWAY_SERVER_PORT: 'gatewayServerPort',
  I_18_N: 'i18N',
  INSTALL_MODULES: 'installModules',
  JHI_PREFIX: 'jhiPrefix',
  JHIPSTER_VERSION: 'jhipsterVersion',
  JWT_SECRET_KEY: 'jwtSecretKey',
  LANGUAGES: 'languages',
  MESSAGE_BROKER: 'messageBroker',
  MICROFRONTEND: 'microfrontend',
  MICROFRONTENDS: 'microfrontends',
  NATIVE_LANGUAGE: 'nativeLanguage',
  NPM: 'npm',
  OTHER_MODULES: 'otherModules',
  PACKAGE_NAME: 'packageName',
  PACKAGE_FOLDER: 'packageFolder',
  PROD_DATABASE_TYPE: 'prodDatabaseType',
  REACTIVE: 'reactive',
  REMEMBER_ME_KEY: 'rememberMeKey',
  SEARCH_ENGINE: 'searchEngine',
  SERVER_PORT: 'serverPort',
  SERVICE_DISCOVERY_TYPE: 'serviceDiscoveryType',
  SKIP_CLIENT: 'skipClient',
  SKIP_GIT: 'skipGit',
  SKIP_INSTALL: 'skipInstall',
  SKIP_SERVER: 'skipServer',
  SKIP_USER_MANAGEMENT: 'skipUserManagement',
  TEST_FRAMEWORKS: 'testFrameworks',
  WEBSOCKET: 'websocket',
  WITH_ENTITIES: 'withEntities',
  ENABLE_GRADLE_ENTERPRISE: 'enableGradleEnterprise',
  GRADLE_ENTERPRISE_HOST: 'gradleEnterpriseHost',
  EUREKA: 'eureka',
  CONSUL: 'consul',
  KAFKA: 'kafka',
  NO: 'no',
  FALSE: false,
  CAFFEINE: 'caffeine',
  EHCACHE: 'ehcache',
  HAZELCAST: 'hazelcast',
  INFINISPAN: 'infinispan',
  MEMCACHED: 'memcached',
  REDIS: 'redis',
  ANGULAR_X: 'angularX',
  ANGULAR: 'angular',
  REACT: 'react',
  VUE: 'vue',
  SVELTE: 'svelte'
};

const constants = {
  INTERPOLATE_REGEX: /<%:([\s\S]+?)%>/g,
  DOCKER_DIR: `${MAIN_DIR}docker/`,
  SERVER_MAIN_SRC_DIR: `${MAIN_DIR}java/`,
  SERVER_MAIN_RES_DIR: `${MAIN_DIR}resources/`,
  SERVER_TEST_SRC_DIR: `${TEST_DIR}java/`,
  SERVER_TEST_RES_DIR: `${TEST_DIR}resources/`,
  YBDB_REL_VERSION: `yugabytedb/yugabyte:${YB_VERSION}`,
  YSQL_DRIVER_VERSION: '42.3.5-yb-3',
  YBDB_DRIVER: 'com.yugabyte.Driver',
  YCQL_DRIVER_VERSION: '4.6.0-yb-12',
  YBDB_VERSION: '1.0.4',
  YBDB_TC: '1.17.6',
};

const k8s = {
  KUBERNETES_POLICY_API_VERSION: 'policy/v1',
  KUBERNETES_CORE_API_VERSION: 'v1',
  KUBERNETES_STATEFULSET_API_VERSION: 'apps/v1',
  KUBERNETES_JOB_API_VERSION: 'batch/v1',
};

const databaseData = {
  [Types.POSTGRESQL]: {
    name: 'PostgreSQL',
    tableNameMaxLength: 63,
    constraintNameMaxLength: 63,
    protocolSuffix: 'yugabytedb://',
    port: ':5433/',
    r2dbc: {
      protocolSuffix: 'postgresql://',
    },
  },
};

module.exports = {
  Types,
  constants,
  databaseData,
  k8s,
};
